#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  11 Mai 2020                        #
#-------------------------------------------------#
# Topic:       6DOF and AMI within a VAWT         #
# OpenFOAM:    7.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-7.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Extract feature edges for the regionSTL"
surfaceFeatures >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Copy the eMesh for the AMI (pre-build with Blender)"
cp cad/blenderModifiedAMI.eMesh constant/triSurface/AMI.eMesh


#------------------------------------------------------------------------------
echo -e "   - Decompose mesh for faster meshing"
decomposePar -force >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing using snappyHexMesh (~ 3 minute)"
mpirun -np 4 snappyHexMesh -overwrite -parallel >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Reconstruct the mesh"
reconstructParMesh -constant >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Modify boundaries for AMI"
createPatch -overwrite  >> logMeshing
rm -rf 0 constant/polyMesh/sets


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
if [ `which pimpleFoam` ]
then

    #--------------------------------------------------------------------------
    echo -e "   - Decompose the mesh"
    decomposePar -force > logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Renumber the mesh / important for big meshes -> speed-up"
    mpirun -np 4 renumberMesh -overwrite -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Start simulation (this will take 24 h for 0.05 s)"
    mpirun -np 4 pimpleFoam -parallel >> logSolve


    #--------------------------------------------------------------------------
else

    #--------------------------------------------------------------------------
    echo -en "   - Can not start simulation, '${RED}pimpleFoam$NC'"
    echo -e " not available"


    #--------------------------------------------------------------------------
fi


#------------------------------------------------------------------------------
echo -e "   - End\n\n"


#------------------------------------------------------------------------------
